# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b4f334ccad252ecd48e72ca51ef1b3ce"
name = "delivery-custom-function"
handle = "delivery-custom-function-1"
application_url = "https://spencer-outlet-hp-exploring.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_products"

[auth]
redirect_urls = [
  "https://spencer-outlet-hp-exploring.trycloudflare.com/auth/callback",
  "https://spencer-outlet-hp-exploring.trycloudflare.com/auth/shopify/callback",
  "https://spencer-outlet-hp-exploring.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
